### ISSUE TITLE
Add a scratch space to NWB file

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#1024]
## 2) Feature Request
Add a scratch space for saving arbitrary datasets to an NWBFile. 

### Problem/Use Case
NWB is cumbersome as a format for day-to-day work. There is a lot of overheard to save one-off analysis results to an NWB file. To save new dataset, a user has write an extension. This is a lot of work for a result that may just be tossed out.

By adding data to a place called something like 'scratch' the user is implicitly agreeing that this data should not be shared.

### ToDos

- [x] https://github.com/NeurodataWithoutBorders/nwb-schema/issues/286
- [x] Add class for scratch NWBData
- [x] Add methods for adding to scratch space
  - should accept an `numpy.ndarray`, `pandas.DataFrame`, `NWBContainer` or `NWBData`
- [x] Add method for getting from scratch space
  - (maybe) should return data as `numpy.ndarray` (if stored as `NWBData`) or `pandas.DataFrame` (if stored as a `DynamicTable`

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
