### ISSUE TITLE
[Umbrella Feature]: Upgrade validation methods

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1808]
### What would you like to see added to PyNWB?

Breaking changes (release in PyNWB 3.0)
- [x] https://github.com/NeurodataWithoutBorders/pynwb/issues/1807
- [ ] https://github.com/hdmf-dev/hdmf/issues/608 and related https://github.com/hdmf-dev/hdmf/issues/525
- [x] Move `pynwb.validate` into module `pynwb.validation` and other organizational changes https://github.com/NeurodataWithoutBorders/pynwb/pull/1493

Non-breaking changes that would be good to do in this breaking change:
- [x] https://github.com/NeurodataWithoutBorders/pynwb/issues/1756
- [x] https://github.com/NeurodataWithoutBorders/pynwb/issues/1179
- [ ] https://github.com/NeurodataWithoutBorders/pynwb/issues/942

There are a number of other validation-related issues and feature enhancements that we could tackle if time permits:
https://github.com/hdmf-dev/hdmf/issues?q=is%3Aopen+label%3A%22topic%3A+validator%22+sort%3Aupdated-desc
https://github.com/NeurodataWithoutBorders/pynwb/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22topic%3A+validator%22

Please suggest other features to bundle into this development.

### What solution would you like?

n/a

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Also related @stephprince https://github.com/NeurodataWithoutBorders/pynwb/issues/1009 or clear all loaded namespaces or something.

**Comment by rly** [comment]
Also related with namespaces https://docs.google.com/document/d/1DB1dg6PEDW40Iafj-kX-y_OZJsqyne7Edah82n17zoo/edit#heading=h.k9x5xabqgniy
